// <auto-generated />
using System;
using Maliev.CountryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.CountryService.Data.Migrations
{
    [DbContext(typeof(CountryDbContext))]
    [Migration("20260106142107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.CountryService.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("text")
                        .HasColumnName("changes");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_audit_logs_country_id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Maliev.CountryService.Data.Entities.BulkImportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("failed_records");

                    b.Property<string>("PayloadData")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_data");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("processed_records");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id")
                        .HasName("pk_bulk_import_jobs");

                    b.ToTable("bulk_import_jobs");
                });

            modelBuilder.Entity("Maliev.CountryService.Data.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("double precision")
                        .HasColumnName("area_km2");

                    b.Property<string>("Borders")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("borders");

                    b.Property<string>("CallingCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calling_codes");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capital");

                    b.Property<string>("CoatOfArms")
                        .HasColumnType("jsonb")
                        .HasColumnName("coat_of_arms");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currencies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("currencies");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Demonym")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("demonym");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<double?>("GiniCoefficient")
                        .HasColumnType("double precision")
                        .HasColumnName("gini_coefficient");

                    b.Property<bool>("Independent")
                        .HasColumnType("boolean")
                        .HasColumnName("independent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso2")
                        .IsFixedLength();

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("iso3")
                        .IsFixedLength();

                    b.Property<bool>("Landlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("landlocked");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_utc");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("numeric_code");

                    b.Property<string>("OfficialName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("official_name");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("Subregion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subregion");

                    b.Property<string>("Timezones")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("timezones");

                    b.Property<string>("TopLevelDomains")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_level_domains");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("translations");

                    b.Property<bool>("UnMember")
                        .HasColumnType("boolean")
                        .HasColumnName("un_member");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Iso2")
                        .IsUnique();

                    b.HasIndex("Iso3")
                        .IsUnique()
                        .HasFilter("iso3 IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Maliev.CountryService.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Maliev.CountryService.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_audit_logs_countries_country_id");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
